### ISSUE TITLE
Add env var to control debug level

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/concurrent_cilk#5]
This should just be a matter of initializing a global variable to be equal to the value of some environment variable (say `IVAR_DBG`), and then `IVAR_DBG_PRINT` if it is compiled in at all, can check that global variable.

**Comment by adk9** [comment]
We added this at some point. The debug level can now be controlled at runtime using the CCILK_DEBUG env var.

The available debug levels are:
IVAR       1
CILKIO     2
CONCURRENT 4
FRAME      8
